"""empty message

Revision ID: 62695497e424
Revises: ee1a4048c98f
Create Date: 2023-03-04 21:16:19.118893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62695497e424'
down_revision = 'ee1a4048c98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint('User_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('User_username_key', ['username'])

    # ### end Alembic commands ###
