"""empty message

Revision ID: 984653beee9d
Revises: 833eba1f3928
Create Date: 2023-03-04 21:24:12.079813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984653beee9d'
down_revision = '833eba1f3928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
